import type { DecisionRecord, QueueItem, RetentionSettings } from "./types";

export const fixtureRetention: RetentionSettings = {
  days: 30,
  storeActorLabels: false,
  fixtureMode: true,
  lastCleanupAt: "2026-05-21T00:00:00.000Z",
};

export const fixtureQueueItems: QueueItem[] = [
  {
    id: "t3_fixture_legal_anecdote",
    thingType: "post",
    title: "Employer asking me to sign an odd repayment agreement",
    body: "I am in California and my manager says I need to sign a training repayment letter. Is this legal advice or just workplace venting?",
    authorLabel: "new contributor",
    reports: ["legal-advice", "needs-source"],
    ruleSignals: ["legal-advice", "jurisdiction"],
    createdAt: "2026-05-21T00:21:00.000Z",
    source: "fixture",
  },
  {
    id: "t1_fixture_civility",
    thingType: "comment",
    title: "Heated reply in market crash thread",
    body: "This reply calls another user a scammer and repeats an unverified accusation without evidence.",
    authorLabel: "regular commenter",
    reports: ["civility", "accusation"],
    ruleSignals: ["civility", "evidence"],
    createdAt: "2026-05-21T00:26:00.000Z",
    source: "fixture",
  },
  {
    id: "t3_fixture_self_promo",
    thingType: "post",
    title: "Free spreadsheet for debt payoff",
    body: "A link post to a personal site with a useful spreadsheet but no disclosure and repeated domain history.",
    authorLabel: "tool maker",
    reports: ["self-promo", "external-link"],
    ruleSignals: ["self-promo", "disclosure"],
    createdAt: "2026-05-21T00:32:00.000Z",
    source: "fixture",
  },
];

export const fixtureDecisions: DecisionRecord[] = [
  {
    id: "fixture-legal-advice-1",
    thingId: "t3_old_legal_1",
    thingType: "post",
    ruleTag: "legal-advice",
    outcome: "escalated",
    summary: "Allowed as a workplace-process question only after the title was edited away from direct legal advice.",
    template: "We can keep this up if it stays focused on process and jurisdiction. Please avoid asking for a definitive legal outcome.",
    keywords: ["legal-advice", "jurisdiction", "workplace", "process"],
    createdAt: "2026-05-01T17:10:00.000Z",
    expiresAt: "2026-06-01T17:10:00.000Z",
    actorLabel: "senior-mod-a",
    source: "fixture",
  },
  {
    id: "fixture-legal-advice-2",
    thingId: "t3_old_legal_2",
    thingType: "post",
    ruleTag: "jurisdiction",
    outcome: "removed",
    summary: "Removed because the author asked for a direct legal conclusion and omitted location after two reminders.",
    template: "Removed: legal questions need jurisdiction and cannot ask the subreddit to decide your case. You may repost with a process-focused question.",
    keywords: ["jurisdiction", "legal-advice", "location", "repost"],
    createdAt: "2026-05-07T12:40:00.000Z",
    expiresAt: "2026-06-06T12:40:00.000Z",
    actorLabel: "senior-mod-b",
    source: "fixture",
  },
  {
    id: "fixture-source-1",
    thingId: "t3_old_source_1",
    thingType: "post",
    ruleTag: "evidence",
    outcome: "needs-second-review",
    summary: "Held for second review because the claim was plausible but lacked an official source.",
    template: "Please add a primary source or clarify that this is personal experience. A mod will review again after the edit.",
    keywords: ["evidence", "source", "claim", "review"],
    createdAt: "2026-05-10T08:15:00.000Z",
    expiresAt: "2026-06-09T08:15:00.000Z",
    actorLabel: "mod-team",
    source: "fixture",
  },
  {
    id: "fixture-civility-1",
    thingId: "t1_old_civility_1",
    thingType: "comment",
    ruleTag: "civility",
    outcome: "removed",
    summary: "Removed for direct personal accusation without evidence during a high-volume thread.",
    template: "Removed for civility. Critique claims and sources, not other users. You can repost without the accusation.",
    keywords: ["civility", "accusation", "evidence", "thread"],
    createdAt: "2026-05-12T21:04:00.000Z",
    expiresAt: "2026-06-11T21:04:00.000Z",
    actorLabel: "mod-team",
    source: "fixture",
  },
  {
    id: "fixture-self-promo-1",
    thingId: "t3_old_promo_1",
    thingType: "post",
    ruleTag: "self-promo",
    outcome: "approved",
    summary: "Approved after the author added affiliation disclosure and answered questions in-thread.",
    template: "Approved after disclosure. Please keep participating in comments and avoid reposting the same domain this week.",
    keywords: ["self-promo", "disclosure", "external-link", "domain"],
    createdAt: "2026-05-15T16:24:00.000Z",
    expiresAt: "2026-06-14T16:24:00.000Z",
    actorLabel: "senior-mod-a",
    source: "fixture",
  },
];
